{"name": "Проверка ошибки логина пользователя c невалидными значениями полей email, password", "status": "passed", "steps": [{"name": "Логинимся пользователем", "status": "passed", "parameters": [{"name": "email", "value": "'tdrswn'"}, {"name": "password", "value": "'orzffv'"}], "start": 1713482899834, "stop": 1713482900234}], "parameters": [{"name": "email", "value": "'tdrswn'"}, {"name": "password", "value": "'orzffv'"}], "start": 1713482899834, "stop": 1713482900235, "uuid": "ce6b6156-96f5-4cc3-b9f4-d9cadcf456f0", "historyId": "8b29e6705ca6aa7038a695a6a0b60e6b", "testCaseId": "27215d35b8dd7ee84709190e39d85e77", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_with_invalid_credentials_return_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "WIN-VD1QDI3F4U5"}, {"name": "thread", "value": "14400-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}