{"name": "Проверка ошибки логина пользователя c невалидными значениями полей email, password", "status": "passed", "steps": [{"name": "Логинимся пользователем", "status": "passed", "parameters": [{"name": "email", "value": "'vrveyq'"}, {"name": "password", "value": "'vqlefo'"}], "start": 1713482900238, "stop": 1713482900602}], "parameters": [{"name": "email", "value": "'vrveyq'"}, {"name": "password", "value": "'vqlefo'"}], "start": 1713482900238, "stop": 1713482900603, "uuid": "c8a919c6-96e1-4e6b-81b0-e5f01228f092", "historyId": "57a7839beef5ccd72b522bd4775870b9", "testCaseId": "27215d35b8dd7ee84709190e39d85e77", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_with_invalid_credentials_return_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "WIN-VD1QDI3F4U5"}, {"name": "thread", "value": "14400-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}